# Generated by Django 3.2.9 on 2021-12-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applied_Job_Detail', '0004_auto_20211230_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_detail',
        ),
    ]
