# Generated by Django 3.2.9 on 2021-12-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applied_Job_Detail', '0007_auto_20211231_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
