# Generated by Django 3.2.9 on 2021-12-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applied_Job_Detail', '0008_auto_20211231_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('todoid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=1000)),
            ],
        ),
    ]
